### ISSUE TITLE
Extract ChromeStandaloneSetup64.exe ?

### ISSUE THREAD

**Issue by jsEveryDay** [CHEF-KOCH/Chrome-downloader#1]
I was wondering if something could be done regarding the setup. All the user needs to run chrome is Chrome-bin folder which contains all the files necessary.

There's plenty of stuff I don't trust during the setup, ex. Services installer, Task Schedules created etc. Further analysis makes me worried even more, look at the suspicious commands /ping or --initial-client-data=0x70,0x.... etc.
Detailed here https://gist.github.com/jsEveryDay/dbaed225bb8ef58d05e8fb5befcc130f
If you browse the default installation path you will always find a chrome.7z (windows) which contains the full chrome /portable app that chrome saves for repair purposes I guess. The only reference I found on the web was this https://reverseengineering.stackexchange.com/questions/4618/extracting-files-from-google-chrome-offline-installer
I tried to binwalk, I was able to extract a lot of the exe's but not the LZMA package I needed. Any suggestion?
I'd like to automate the chrome update in it's purest form. I don't want to run the setup that applies god knows what to the registry and other files so for now I am stuck using this method I figured out: 
1. Turn on UAC to max.
2. Run setup standalone
3. Before answering UAC go to temp folder, find the *.GMP folder just created
4. Extract the largest file using 7zip => result should be chrome_bin
5. Kill any running exe using powershell filter *google*
6. Anwer UAC -> NO (nothing should happen)

Alternatively (not recommended) => Chrome uses %TMP% env var, not %TEMP%
Create a folder, using ICALCS remove user permissions for DELETE and EXECUTE but leave read/write
Temporarily set %TMP% to new folder
Run setup
Nothing should happen (meanwhile folder will be populated with desired files)
Change TMP path to original and extract the target file from the new folder.

Still, this method doesn't seem clean enough. I was hoping to automate this in linux so I could get the portable chrome without taking any risks in windows. Or alternatively automate this in PowerShell, which I've already done but, i don't know how to "ignore" UAC prompt, proceed with commands and then answer UAC = > NO using ps

Any help would be appreciated, maybe the community will find this useful.

**Comment by CHEF-KOCH** [comment]
Hey!

Before I seriously answer that, just a question. What is wrong with:
* Using Chromium + Chromium updater, both are FOSS and documented
* Using Brave which has the best out-of-the-box experience (well documented, well maintained and there bunch of "update possibilities")
* Ditching Chrome and replace it with Firefox

**Comment by jsEveryDay** [comment]
I truly appreciate your attention, given how busy/important you are. Before I begin with my stupid answer, I want to thank you for what you do and for the bigger/wider dent you're making to privacy invasive billion dollar ad campaigns.

I really hope the answer is not "it cant be done, because of this and that" :( because you got me excited.

1. I do use Chromium, tried to make a switch, gave it 3 months as the only browser, couldn't survive it. Very unstable, weirdest problems, media codecs never reliable. Then thought I'd use it just for development, I would have a successful run for a few months, then update would ruin it, like the code color schema would go away for a week then come back on the next update. To top it all off, one time I spent two nights awake cuz I couldn't get my async promises to execute as required, turns out it was just a chromium bug. And, there's more telemetry in chromium than chrome itself, a lot more logging and usage info is pinged to Mountain View CA, which defeats the purpose of it being a better alternative.

2. Brave, never touched it. Heard the buzz, thought it was just another "vivaldi", "opera" etc. but I keep hearing good stuff so maybe I will try it. Then I heard they'd pay you to see 'some' ads'... ehhh. I'd rather be tracked by google than be tracked by a small company watching me watch ads. But, regardless, ill MITM it and I'll jump on board if you say its good.

3. Firefox, don't have a good rational explanation why I don't like it, never did like it since I was a kid. I was considering it like 5 years ago, then I saw it was making calls to facebook and yahoo, weird right? It was the time when Like buttons were spreading around and social stuff was exciting. But nothing was as horrifying as Vivaldi or Opera, I felt like I was being used as a bot, to run traffic as a proxy.

Yes, firefox is the best option for now, I agree, I've also aid the same thing on gorhill's thread about manifest V3. Ofc is the default browser on my phone, given that uBlock is compatible.
Born 1990  -> 1996 got Win95 + Duke Nukem -> 1997 got dialup (only for Eudora) -> then IE was it (playing flash games) -> Fast Browser -> IE -> Opera was awesome in Nokias, so Opera for 5 years -> tried FireFox nahh -> Apple Safari (win) -> FF a lil -> Chrome.

Lastly, I have 12 extensions running in chrome, 8 of which I have written myself. Never published, storage still syncs perfectly to google as if they were on the store, making switching from Office-Dekstop-Laptop-Phone very easy. I hope I earned my answer.

**Comment by CHEF-KOCH** [comment]
**Chromium**
Can you please re-test and post your findings with "Chromium" on this site: [chromium.woolyss.com](https://chromium.woolyss.com/). I know those guys benchmarking and checking the codecs as well as telemetry after each change. Those guys earned my trust, so it would surprise me if your statement that Chromium uses "more telemetry" than the original Chrome would be true. It's not that I observed. 

Chromium uses same like Chrome the media router feature for Chromecast which is triggered very often, this is not telemetry. I say it because people often asking me about it.

Codec wise I know MS Edge (Chromium) a.k.a. Edgium works best with Netflix. 

**Brave**
Maybe check this [article](https://theprivacyguide1.github.io/why_brave_isnt_bad.html) which debunks all concerns about Brave.

**Firefox**
I guess you should re-try it, a lot of stuff has changed. Yahoo is no longer a partner and there are only connections to the implemented features like pocket (which you can fully disable, same like integrated telemetry).


**ChromeStandaloneSetup64.exe extraction and the problems**
* The problem I see is that your goal is that "strip away" some parts after the extraction process, I can guarantee you that this is not going to work. You basically will get more instability, possible crashes and other problems.
* There is no guarantee that Google is not going to change the compression algo, some parts, files etc without any further mention in their change log which will most likely break the extraction each time they changed something. Personally I do not want to waste my lifetime for "Google quirks" like this.
 
However I consider it, but it's low priority. Due to antitrust reason I highly suggest you use Firefox/Brave, Chromium or MS Edge (Chromium). 

You can be sure I do not suggest someone a software product which I wouldn't use myself....

**Comment by jsEveryDay** [comment]
Thanks man, appreciate your response and Marry Christmas.
That's exactly where I get chromium. Yes more telemetry sometimes, ungoogled versions don't codec nor can you install extensions locally. So it's usually a hit or miss, sure you may get lucky and get a stable release on the first try. I use chromium for watching xxx lol, at times when you update, you get a version with no popup protection, or weird security issues which xxx sites manage to exploit instantly. UDP ports are bocked on the router, Chromium GPO is enabled, Chromecast and other features are disabled on GPO. Some versions of chromium respect GPO for others it doesn't exist. So that's why I got tired of it.
I always have firefox installed. Use it only when I code in production. Cloud9 ide looks best in FF.
MS Edge, never tried it, can't. Stuck on LTSB 1607 permanently, I refuse to move up.

When you work 9-5 in Java (fully backend), it's hard to keep up with browser stuff.
I know the extraction is not easy, even if you manage to do it the next release they'll change the code but at this point I dived in too much and I had to find out how they do it, that's why I thought you'd be the best guy to ask.
